document.addEventListener("DOMContentLoaded", () => {
  const selectDrop = document.querySelector("#country");
  var countryArr = [
    "Bir ülke/bölge seçin…",
    "Afganistan",
    "Åland Adaları",
    "Almanya",
    "Amerika Birleşik Devletleri (ABD)",
    "Amerika Birleşik Devletleri (ABD) Küçük Dış Adaları",
    "Amerikan Samoası",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antartika",
    "Antigua ve Barbuda",
    "Arjantin",
    "Arnavutluk",
    "Avustralya",
    "Avusturya",
    "Azerbaycan",
    "Bahamalar",
    "Bahreyn",
    "Bangladeş",
    "Barbados",
    "Batı Sahra",
    "Belau",
    "Belçika",
    "Belize",
    "Benin",
    "Bermuda",
    "Beyaz Rusya",
    "Birleşik Arap Emirlikleri",
    "Birleşik Krallık (UK)",
    "Bolivya",
    "Bonaire, Saint Eustatius and Saba",
    "Bosna Hersek",
    "Botsvana",
    "Bouvet Adası",
    "Brezilya",
    "Brunei Sultanlığı",
    "Bulgaristan",
    "Burkina Faso",
    "Burundi",
    "Butan",
    "Cape Verde",
    "Cayman Adaları",
    "Cebelitarık",
    "Cezayir",
    "Christmas Adaları",
    "Cibuti",
    "Cocos (Keeling) Adaları",
    "Comoros",
    "Cook Adaları",
    "Curaçao",
    "Çat",
    "Çek Cumhuriyeti",
    "Çin",
    "Danimarka",
    "Dominik Cumhuriyeti",
    "Dominika",
    "Ekvator",
    "Ekvator Ginesi",
    "El Salvador",
    "Endonezya",
    "Eritre",
    "Ermenistan",
    "Estonya",
    "Etiyopya",
    "Falkland Adaları",
    "Faroe Adaları",
    "Fas",
    "Fiji",
    "Fildişi Sahilleri",
    ,
    "Filipinler",
    "Filistin",
    "Finlandiya",
    "Fransa",
    "Fransız Guyanası",
    "Fransız Güney Bölgeleri",
    "Fransız Poliznezyası",
    "Gabon",
    "Gambiya",
    "Gana",
    "Gine",
    "Gine-Bissau Cumhuriyeti",
    "Grenada",
    "Grönland",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guyana",
    "Güney Afrika",
    "Güney Georgia / Sandwich Adaları",
    "Güney Kore",
    "Güney Sudan",
    "Gürcistan",
    "Haiti",
    "Heard Adası ve McDonald Adaları",
    "Hırvatistan",
    "Hindistan",
    "Hint Okyanusu İngiliz Bölgesi",
    "Hollanda",
    "Honduras",
    "Hong Kong",
    "Irak",
    "İran",
    "İrlanda",
    "İspanya",
    "İsrail",
    "İsveç",
    "İsviçre",
    "İtalya",
    "İzlanda",
    "Jamaika",
    "Japonya",
    "Jersey",
    "Kamboçya",
    "Kamerun",
    "Kanada",
    "Karadağ",
    "Katar",
    "Kazakistan",
    "Kenya",
    "Kıbrıs",
    "Kırgızistan",
    "Kiribati",
    "Kolombiya",
    "Kongo (Brazzaville)",
    "Kongo (Kinshasa)",
    "Kostarika",
    "Kuveyt",
    "Kuzey Kore",
    "Kuzey Makedonya",
    "Kuzey Mariana Adaları",
    "Küba",
    "Laos",
    "Lesoto",
    "Letonya",
    "Liberya",
    "Libya",
    "Lihtenştayn",
    "Litvanya",
    "Lübnan",
    "Lüksemburg",
    "Macao",
    "Macaristan",
    "Madagaskar",
    "Malavi",
    "Maldivler",
    "Malezya",
    "Mali",
    "Malta",
    "Man Adası",
    "Marshall Adaları",
    "Martinik",
    "Mayotte",
    "Meksika",
    "Mısır",
    "Mikronezya",
    "Moğolistan",
    "Moldova",
    "Monako",
    "Montserat",
    "Moritanya",
    "Morityus",
    "Mozambik",
    "Myanmar",
    "Namibya",
    "Nauru",
    "Nepal",
    "Nijer",
    "Nijerya",
    "Nikaragua",
    "Niue",
    "Norfolk Adası",
    "Norveç",
    "Orta Afrika Cumhuriyeti",
    "Özbekistan",
    "Pakistan",
    "Panama",
    "Papua Yeni Gine",
    "Paraguay",
    "Peru",
    "Pitcairn Adası",
    "Polonya",
    "Portekiz",
    "Porto Riko",
    "Reunion Adası",
    "Romanya",
    "Ruanda",
    "Rusya Federasyonu",
    "Saint Barthelemy",
    "Saint Pierre ve Miquelon",
    "Saint Vincent ve Grenadinler",
    "Samoa",
    "San Marino",
    "Santa Helena",
    "Santa Kitts ve Nevis",
    "Santa Luçia",
    "Santa Martin (Fransız Kesimi)",
    "Santa Martin (Hollanda bölümü)",
    "Sao Tome and Principe",
    "Senegal",
    "Seyşeller",
    "Sırbistan",
    "Sierra Leone",
    "Singapur",
    "Slovakya",
    "Slovenya",
    "Solomon Adaları",
    "Somali",
    "Sri Lanka",
    "Sudan",
    "Surinam",
    "Suriye",
    "Suudi Arabistan",
    "Svalbard ve Jan Mayen Adaları",
    "Svaziland",
    "Şili",
    "Tacikistan",
    "Tanzanya",
    "Tayland",
    "Tayvan",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad ve Tobago",
    "Tunus",
    "Turks ve Caicos Adaları",
    "Tuvalu",
    "Türkiye",
    "Türkmenistan",
    "Uganda",
    "Ukrayna",
    "Umman",
    "Uruguay",
    "Ürdün",
    "Vanuatu",
    "Vatikan",
    "Venezuela",
    "Vietnam",
    "Virjin Adaları (ABD)",
    "Virjin Adaları (Britanya)",
    "Wallis ve Futuna",
    "Yemen",
    "Yeni Kaledonya",
    "Yeni Zelanda",
    "Yunanistan",
    "Zambia",
    "Zimbabve",
  ];
  let output = "";
  countryArr.forEach((country) => {
    output += `<option value="${country}">${country}</option>`;
  });
  selectDrop.innerHTML = output;
});

let personalOption = document.querySelector("#personal");
let businessOption = document.querySelector("#business");

let personalInputs = document.querySelector("#personalInputs");
let businessInputs = document.querySelector("#businessInputs");

document
  .getElementById("billing_selection")
  .addEventListener("change", function () {
    if (this.value == "Bireysel") {
      businessInputs.style.display = "none";
      personalInputs.style.display = "block";
    } else {
      personalInputs.style.display = "none";
      businessInputs.style.display = "block";
    }
  });

personalOption.addEventListener("click", function () {});
businessOption.addEventListener("click", function () {});
